Basic_Authentiocation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path("admin/", admin.site.urls), path("app/", include("aut.urls"))]

aut/urls.py
from django.urls import path
from .views import *

app_name = "aut"

# urlpatterns = [
#     path("", home, name="home"),
#     path("login/", login_user, name="login"),
#     path("logout/", logout_user, name="logout"),
#     path("registration/", registration_user, name="regisregistration"),
# ]

urlpatterns = [
    path("", home, name="home"),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
    path(
        "registration/", registration_user, name="registration"
    ),  # Updated name parameter
]

aut/models.py
from django.db import models

# Create your models here.

aut/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def home(req):
    return render(req, "aut/home.html")


def registration_user(req):
    if req.method == "POST":
        fname = req.POST.get("fname")
        lname = req.POST.get("lname")
        username = req.POST.get("username")
        email = req.POST.get("email")
        password1 = req.POST.get("password1")
        password2 = req.POST.get("password2")
        if password1 == password2:
            if User.objects.filter(username = username).exists():
                messages.info(req, "username taken")
                return redirect("aut:registration")
            elif User.objects.filter(email = email).exists():
                messages.info(req, "email taken")
                return redirect("aut:registration")
            else:
                print("🔴🔴")
                user = User.objects.create_user(
                    username=username,
                    email=email,
                    password=password1,
                    first_name = fname,
                    last_name = lname,
                )
                # user.fname=fname
                user.lname=lname
                user.save()
                print("🟢")
                return redirect("aut:login")
        else:
            print("1️⃣")
            return redirect("aut:registration")
    print("2️⃣")
    return render(req, "aut/registration.html")


def login_user(req):
    if req.method == "POST":
        username = req.POST.get("username")
        password = req.POST.get("password")
        print(username,password)
        user = authenticate(req ,username=username, password=password)
        print(user)
        if user is not None:
            login(req, user)
            return redirect("http://127.0.0.1:8000/app/")
        else:
            print("1️⃣")
            messages.error(req , "credential is invalid")
            return redirect("aut:login")
    print("2️⃣")
    return render(req, "aut/login.html")
            

def logout_user(req):
    logout(req)
    return redirect("/")

aut/templates/aut/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>home</title>
    </head>

    <body>
        {% if user.is_authenticated %} hello, {{ user.first_name }}
        <a href="{% url 'aut:logout' %}">logout</a> &nbsp; {% else %}
        <a href="{% url 'aut:login' %}">login</a> &nbsp;
        <a href="{% url 'aut:registration' %}">signup</a> &nbsp; {% endif %}
    </body>
</html>

aut/templates/aut/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>login</title>
    </head>

    <body>
        <form action="" method="post">
            {% csrf_token %}
            <input
                name="username"
                placeholder="username"
                required
                type="text"
            /><br />
            <input
                name="password"
                placeholder="password"
                required
                type="password"
            /><br />
            <input type="submit" />
        </form>
        <div>
            {% for message in messages %}
            <h3>{{message}}</h3>
            {% endfor %}
        </div>
    </body>
</html>

aut/templates/aut/registration.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>registration</title>
    </head>
    <body>
        <form action="" method="POST">
            {% csrf_token %}
            <input
                name="fname"
                placeholder="first name"
                required
                type="text"
            /><br />
            <input
                name="lname"
                placeholder="last name"
                required
                type="text"
            /><br />
            <input
                name="username"
                placeholder="username"
                required
                type="text"
            /><br />
            <input
                name="email"
                placeholder="email"
                required
                type="email"
            /><br />
            <input
                name="password1"
                placeholder="password"
                required
                type="password"
            /><br />
            <input
                name="password2"
                placeholder=" confirm password"
                type="password"
            /><br />
            <input type="submit" />
        </form>
        <div>
            {% for message in messages %}
            <h3>{{message}}</h3>
            {% endfor %}
        </div>
    </body>
</html>